name: Assign PR Author
on:
  pull_request:
    types: [opened, converted_to_draft, reopened, ready_for_review]

jobs:
  AssignAuthor:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            const { owner, repo, number } = context.issue;
            const { data: pull_request } = await github.rest.pulls.get({
                owner,
                repo,
                pull_number: number
            });
            const author = pull_request.user.login;
            console.log(`Assigning PR author (${author}) to PR #${number}`);
            if (author.includes('[bot]') || author.includes('dependabot') || author.includes('dependabot')) {
                console.log(`PR author is a bot, skipping assignment`);
                return;
            }
            await github.rest.issues.addAssignees({
                owner,
                repo,
                issue_number: number,
                assignees: [author]
            });
