name: Assign Reviewers
on:
  issue_comment:
    types: [created]

jobs:
  AssignReviewers:
    if: (contains(github.event.comment.body, '/r? @') && github.event.issue.pull_request != null)
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            const { owner, repo, number } = context.issue;
            const commentBody = context.payload.comment.body;
            const mentionRegex = /\/r\? ((@\w+ ?)+)/;
            const match = commentBody.match(mentionRegex);
            if (!match) {
              console.log('No username found in comment.');
              return;
            }
            const usernames = match[1].split(' ').filter(Boolean);
            const reviewers = usernames.map(username => username.replace('@', ''));
            await github.rest.pulls.requestReviewers({
                owner,
                repo,
                pull_number: number,
                reviewers: reviewers
            });
