name: Comment Handle Runner
on:
  issue_comment:
    types: [created]

jobs:
  CommentHandle:
    if: (contains(github.event.comment.body, '/queue-merge') && github.event.issue.pull_request != null)
    runs-on: ubuntu-latest
    steps:
      - run: echo "Comment Handle Runner"
      - run: echo "${{ github.ref }}"
        name: ref
      - run: echo "${{ github.sha }}"
        name: sha
      - uses: actions/github-script@v7
        name: merge_commit_sha
        with:
          script: |
            const { owner, repo, number } = context.issue;
            const { data } = await github.rest.pulls.get({
              owner,
              repo,
              pull_number: number
            });
            console.log(data.merge_commit_sha);
      - uses: actions/github-script@v7
        name: mergeable
        with:
          script: |
            const { owner, repo, number } = context.issue;
            const { data } = await github.rest.pulls.get({
              owner,
              repo,
              pull_number: number
            });
            if (data.mergeable === false) {
              throw new Error('The pull request is not mergeable due to conflicts.');
            } else {
              console.log('The pull request is mergeable.');
            }
      - uses: actions/github-script@v7
        name: master
        with:
          script: |
            const { owner, repo, number } = context.issue;
            const { data } = await github.rest.repos.getBranch({
              owner,
              repo,
              branch: 'master'
            });
            console.log(data.commit.sha);
      - uses: actions/github-script@v7
        with:
          script: |
            const runUrl = `https://github.com/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}`;
            console.log(`Action run URL: ${runUrl}`);

  RunJobs:
    runs-on: ubuntu-latest
    needs: [CommentHandle]
    concurrency:
      group: queue-merge
      cancel-in-progress: false
    steps:
      - uses: actions/checkout@v4
      - uses: actions/github-script@v7
        id: get_base_branch
        with:
          script: |
            const { owner, repo, number } = context.issue;
            const { data } = await github.rest.pulls.get({
              owner,
              repo,
              pull_number: number
            });
            console.log(`Base branch: ${data.base.ref}`);
            return data.base.ref;
      - env:
          GH_TOKEN: ${{ github.token }}
        run: |
          git log --oneline |head -n 10;
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com";
          git config --global user.name "github-actions[bot]";
          # delete auto branch
          git pull origin ${{ steps.get_base_branch.outputs.result }};
          gh pr checkout ${{ github.event.issue.number }} && \
          git merge --allow-unrelated-histories ${{ steps.get_base_branch.outputs.result }} && git show HEAD
      - run: git show HEAD
      - run: echo "${{ github.ref }}"
      - run: echo "${{ github.sha }}"
      - uses: actions/github-script@v7
        with:
          script: |
            const { owner, repo, number } = context.issue;
            const { data } = await github.rest.pulls.get({
              owner,
              repo,
              pull_number: number
            });
            console.log(data.merge_commit_sha);
      - uses: actions/github-script@v7
        with:
          script: |
            const { owner, repo, number } = context.issue;
            const { data } = await github.rest.pulls.get({
              owner,
              repo,
              pull_number: number
            });
            if (data.mergeable === false) {
              throw new Error('The pull request is not mergeable due to conflicts.');
            } else {
              console.log('The pull request is mergeable.');
            }
      - uses: actions/github-script@v7
        name: master
        with:
          script: |
            const { owner, repo, number } = context.issue;
            const { data } = await github.rest.repos.getBranch({
              owner,
              repo,
              branch: 'master'
            });
            console.log(data.commit.sha);
      - uses: actions/github-script@v7
        with:
          script: |
            const script = require('${{ github.workspace }}/.github/scripts/wait.js')
            await script({ context })
      - uses: actions/github-script@v7
        with:
          script: |
            const { owner, repo, number } = context.issue;
            const { data } = await github.rest.pulls.get({
              owner,
              repo,
              pull_number: number
            });
            console.log(data.merge_commit_sha);
      - uses: actions/github-script@v7
        with:
          script: |
            const { owner, repo, number } = context.issue;
            const { data } = await github.rest.pulls.get({
              owner,
              repo,
              pull_number: number
            });
            if (data.mergeable === false) {
              throw new Error('The pull request is not mergeable due to conflicts.');
            } else {
              console.log('The pull request is mergeable.');
            }
      - uses: actions/github-script@v7
        name: master
        with:
          script: |
            const { owner, repo, number } = context.issue;
            const { data } = await github.rest.repos.getBranch({
              owner,
              repo,
              branch: 'master'
            });
            console.log(data.commit.sha);
