name: Diff

on:
  issue_comment:
    types: [created]
  # Debug用途
  workflow_dispatch:

env:
    NODE_VERSION: 18.15

jobs:
  screenshot:
    runs-on: ubuntu-22.04
    if: ${{ github.event.issue.pull_request }} && startsWith(github.event.comment.body, '/screenshot') || github.event_name == 'workflow_dispatch'
    permissions:
      contents: read
      pull-requests: write
      issues: write
      actions: write
    steps:
    - uses: actions/checkout@v3
    - run: make diff-screenshot PR=${{ github.event.issue.number }}> ./my-diff
    - uses: actions/upload-artifact@v3
      with:
        name: diff
        path: ./my-diff
        retention-days: 2
    - name: Diff見れるURLを見せるぞ
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        URL: ${{ github.event.issue.html_url }}
      run: |
        RUN_ID=gh run list --limit 1 --workflow=Diff --json databaseId|jq -r '.[0].databaseId'
        echo https://github.com/yamachu/play-actions/actions/runs/${RUN_ID} のArtifactsのDiffを確認してね > ./artifacts

        gh pr comment -F ./artifacts "${URL}"
