name: Diff

on:
  issue_comment:
    types: [created]
  # Debug用途
  workflow_dispatch:

env:
    NODE_VERSION: 18.15

jobs:
  screenshot:
    runs-on: ubuntu-22.04
    if: ${{ github.event.issue.pull_request }} && startsWith(github.event.comment.body, '/screenshot') || github.event_name == 'workflow_dispatch'
    permissions:
      contents: read
      pull-requests: write
      issues: write
      actions: write
    steps:
    - run: cat $GITHUB_EVENT_PATH
    # see: https://dev.classmethod.jp/articles/github-actions-get-diff-files-on-pr-events/
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - name: fetch master
      run: git fetch origin master:master
    - run: make diff-screenshot > ./my-diff
    - uses: actions/upload-artifact@v3
      with:
        name: diff
        path: ./my-diff
        retention-days: 2
    - name: Diff見れるURLを見せるぞ
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        URL: ${{ github.event.issue.html_url }}
      run: |
        gh api \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          /repos/yamachu/play-actions/actions/artifacts | \
        jq '.artifacts[] | select(.workflow_run.head_sha == "${{ github.sha }}") | .archive_download_url' > ./artifacts
        gh pr comment -F ./artifacts "${URL}"
