name: Nested

on:
  workflow_dispatch:

jobs:
  base:
    runs-on: ubuntu-latest
    steps:
      - run: echo hello
      - run: echo "my_result=true" >> "$GITHUB_OUTPUT"

  foo:
    runs-on: ubuntu-latest
    needs: base
    steps:
      - run: exit 1

  bar:
    runs-on: ubuntu-latest
    needs: [base, foo]
    if: ${{ always() }}
    steps:
      - run: echo "こんにちは"
      - run: echo ${{ needs.base.outputs.my_result }}
      - run: |
        [ "${{ needs.base.outputs.my_result }}" = "true" ] && exit 0 || exit 1
