name: Comment Handle Runner
on:
  issue_comment:
    types: [created]

jobs:
  CommentHandle:
    if: (contains(github.event.comment.body, '/qm') && github.event.issue.pull_request != null)
    runs-on: ubuntu-latest
    steps:
      - uses: yamachu/merge-queue-action/precheck@main
        with:
          required-codeowners: 'false'
      - name: Dispatch workflow via GitHub CLI
        run: |
          # FIXME: 本来は --ref auto.tmp などで行いたいが、auto.tmp への push は後段のジョブで行うため、default branch に紐づいてしまう
          gh workflow run -R ${{ github.event.repository.full_name }} -f issue_number=${{ github.event.issue.number }} testing-queue.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
