name: Comment Handle Runner
on:
  issue_comment:
    types: [created]

jobs:
  CommentHandle:
    if: (contains(github.event.comment.body, '/qm') && github.event.issue.pull_request != null)
    runs-on: ubuntu-latest
    steps:
      - uses: yamachu/merge-queue-action/precheck@main
        with:
          required-codeowners: 'false'

  RunJobs:
    runs-on: ubuntu-latest
    needs: [CommentHandle]
    concurrency:
      group: queue-merge
      cancel-in-progress: false
    # steps:
    #   - uses: yamachu/merge-queue-action/testing@main
    #     with:
    #       github-token: ${{ secrets.GITHUB_TOKEN }}
    #       required-ci-checks: 'xxxxx'
  
  TEST:
    uses: ./.github/workflows/script-worker.yml
    concurrency:
      group: queue-merge
      cancel-in-progress: false
    needs: [RunJobs]

  AFTER:
    runs-on: ubuntu-latest
    needs: [TEST]
    concurrency:
      group: queue-merge
      cancel-in-progress: false
    steps:
      - run: echo "AFTER"
