# This is a basic workflow to help you get started with Actions

name: Script Worker

# Controls when the workflow will run
on:
  workflow_dispatch:
  workflow_call:
    inputs:
      checkout-ref:
        description: 'The ref to checkout'
        required: false
        type: string

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  ScriptWorker:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ inputs.checkout-ref || github.head_ref }}
      - uses: actions/github-script@v6
        with:
          script: |
            const script = require('${{ github.workspace }}/.github/scripts/wait.js')
            await script({ context })
