name: Testing Queue Runner
on:
  workflow_dispatch:
    inputs:
      repo:
        description: 'Repository name'
        required: true
      owener:
        description: 'Repository owner'
        required: true
      issue_number:
        description: 'Issue number'
        required: true
concurrency:
  group: queue-merge
  cancel-in-progress: false

jobs:
  PreTesting:
    runs-on: ubuntu-latest
    outputs:
      base-branch: ${{ steps.pretesting.outputs.base-branch }}
      base-branch-sha: ${{ steps.pretesting.outputs.base-branch-sha }}
    steps:
      - uses: yamachu/merge-queue-action/pretesting@main
        id: pretesting
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          pr-number: ${{ github.event.inputs.issue_number }}

  Test:
    uses: ./.github/workflows/script-worker.yml
    needs: [PreTesting]

  PostTesting:
    runs-on: ubuntu-latest
    needs: [PreTesting, Test]
    steps:
      - uses: yamachu/merge-queue-action/posttesting@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          base-branch: ${{ needs.PreTesting.outputs.base-branch }}
          base-branch-sha: ${{ needs.PreTesting.outputs.base-branch-sha }}
          pr-number: ${{ github.event.inputs.issue_number }}